### ISSUE TITLE
AT25SF128A bootloader don't work on Arduino Nano Connect

### ISSUE THREAD

**Issue by TFleury** [rp-rs/rp2040-boot2#19]
I've an Arduino Nano Connect and the board don't boot with "BOOT_LOADER_AT25SF128A".
Swapping to "BOOT_LOADER_W25Q080" the board runs as expected.

As the [arduino_nano_connect](https://github.com/rp-rs/rp-hal/tree/main/boards/arduino_nano_connect) BSP includes "BOOT_LOADER_AT25SF128A" this makes the package unusable.

It's broken both on v0.2.0 and v0.2.1.

**Comment by jannic** [comment]
Can you check what type of flash chip is on your nano connect board?
According to https://store-usa.arduino.cc/collections/boards/products/arduino-nano-rp2040-connect, it should be an AT25SF128A-MHB-T, so BOOT_LOADER_AT25SF128A looks correct.
However, perhaps there are different versions of that board using different flash chips? If that's the case, just changing the boot loader in the BSP may break booting on the other version.

**Comment by TFleury** [comment]
Thank you for your answer, it seems you're right the flash chip is an IS25LP128F. It's not mentioned on Arduino website.

Maybe the [arduino_nano_connect](https://github.com/rp-rs/rp-hal/tree/main/boards/arduino_nano_connect) BSP should depend on a more generic bootloader.

**Comment by jannic** [comment]
> Maybe the [arduino_nano_connect](https://github.com/rp-rs/rp-hal/tree/main/boards/arduino_nano_connect) BSP should depend on a more generic bootloader.

That's a good suggestion. Let's keep the ticket open to track that.

**Comment by jannic** [comment]
Oops, I didn't notice that a change to the BSP should be tracked in a different repo. → Now opened https://github.com/rp-rs/rp-hal/issues/503 for that.
