### ISSUE TITLE
Delete develop branch

### ISSUE THREAD

**Issue by thejpster** [rp-rs/rp2040-boot2#21]
We should either merge PRs into develop and save the main branch for releases (this is the *git flow* method). Or we should delete the develop branch.

**Comment by jannic** [comment]
I already wrote it in the pull request comment, but it belongs here:
Is a separate develop branch useful for this crate? I don't really think so, as I don't expect much development here. I agree that we should delete it if we don't use it.

**Comment by jannic** [comment]
I deleted the branch. The last head of the develop branch, 700011cfd403690834ec50069f0fae45efc03a50, had contents identical to the tag v0.1.2.
